import { ExplanationSection } from '@/components/explanation/ExplanationSection';
import { KeyFindings } from '@/components/explanation/KeyFindings';
import { Accordion } from '@/components/ui/accordion';
import type { ExplanationOutput } from '@/types/explanation';
import {
  Bot,
  BrainCircuit,
  Calendar,
  CheckCircle2,
  Clock,
  Sparkles,
} from 'lucide-react';

interface ExplanationDisplayProps {
  explanation: ExplanationOutput;
}

export function ExplanationDisplay({ explanation }: ExplanationDisplayProps) {
  const { content, metadata } = explanation;

  // Format date
  const generatedDate = new Date(explanation.generatedAt).toLocaleString();

  // Convert confidence to percentage
  const confidencePercent = metadata.confidenceInExplanation
    ? Math.round(metadata.confidenceInExplanation * 100)
    : null;

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Header Info */}
      <div className="flex flex-col gap-4 rounded-lg border bg-muted/30 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Bot className="h-4 w-4" />
          <span>
            Generated by {explanation.provider} ({explanation.modelUsed})
          </span>
          <span className="select-none text-muted-foreground/30">•</span>
          <Clock className="h-4 w-4" />
          <span>{generatedDate}</span>
        </div>

        {confidencePercent && (
          <div className="flex items-center gap-1.5 rounded-full bg-green-500/10 px-3 py-1 text-sm font-medium text-green-600 dark:text-green-400">
            <CheckCircle2 className="h-4 w-4" />
            <span>{confidencePercent}% Confidence</span>
          </div>
        )}
      </div>

      {/* Summary */}
      <div className="relative overflow-hidden rounded-xl border bg-card p-6 shadow-sm">
        <div className="absolute right-0 top-0 -mr-16 -mt-16 h-32 w-32 rounded-full bg-primary/10 blur-3xl" />

        <h3 className="mb-3 flex items-center gap-2 text-lg font-semibold">
          <Sparkles className="h-5 w-5 text-primary" />
          Analysis Summary
        </h3>
        <p className="text-base leading-relaxed text-muted-foreground">
          {content.summary}
        </p>
      </div>

      {/* Key Findings */}
      {content.keyFindings && content.keyFindings.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-lg font-semibold flex items-center gap-2">
            <BrainCircuit className="h-5 w-5" />
            Key Findings
          </h3>
          <KeyFindings findings={content.keyFindings} />
        </div>
      )}

      {/* Detailed Analysis Sections */}
      <div className="space-y-3">
        <h3 className="text-lg font-semibold">Detailed Breakdown</h3>
        <Accordion type="single" collapsible className="w-full">
          {content.detailedExplanation.sections
            .sort((a, b) => a.order - b.order)
            .map((section, index) => (
              <ExplanationSection
                // biome-ignore lint/suspicious/noArrayIndexKey: Order is stable
                key={index}
                section={section}
              />
            ))}
        </Accordion>
      </div>

      {/* Footer / Limitations */}
      {(content.limitations?.length ?? 0) > 0 && (
        <div className="mt-8 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">
          <h4 className="mb-2 font-medium text-foreground">Limitations</h4>
          <ul className="list-inside list-disc space-y-1">
            {content.limitations?.map((limitation, i) => (
              // biome-ignore lint/suspicious/noArrayIndexKey: Static list
              <li key={i}>{limitation}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
